# docker compose.yml
version: '3.7'
services:
  scanner:
    build: .
    volumes:
      - .:/app
    environment:
      - TOKEN=your_token_here
      - TG_TOKEN=your_telegram_bot_token_here
      - CHAT_ID=your_chat_id_here
      - COLO=SIN # optional - default is SIN (Singapore)
